apiVersion: apps/v1
kind: Deployment
metadata:
  name: yts-users
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-rds: $(ENVIRONMENT)/database/users/creds/users
