apiVersion: apps/v1
kind: Deployment
metadata:
  name: yts-users
spec:
  template:
    metadata:
      # yamllint disable rule:line-length
      annotations:
        vault.hashicorp.com/agent-inject-secret-sms_password: ""
        vault.hashicorp.com/agent-inject-template-sms_password: |
          {{- with secret "transit/git/decrypt/team5-ycs-users" "ciphertext=vault:v1:r81oLxNfr/fg1kP1XOVYiIonCgIzCVJzdmxWR7Pz3tqi4Zqo" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: PASSWORD_ALFA_NUMERIC_SPECIAL_CHARS
          {{ .Data.plaintext }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-sms_username: ""
        vault.hashicorp.com/agent-inject-template-sms_username: |
          {{- with secret "transit/git/decrypt/team5-ycs-users" "ciphertext=vault:v1:uszxILD2VzqHyDJAo4zw9my8I6Nnmkoiiq06cTSHMhbl+xqLKgQZOzA2" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: PASSWORD_ALFA_NUMERIC_SPECIAL_CHARS
          {{ .Data.plaintext }}
          {{- end -}}
