apiVersion: apps/v1
kind: Deployment
metadata:
  name: yts-users
spec:
  template:
    metadata:
      # yamllint disable rule:line-length
      annotations:
        vault.hashicorp.com/agent-inject-secret-sms_password: ""
        vault.hashicorp.com/agent-inject-template-sms_password: |
          {{- with secret "transit/git/decrypt/team9-ycs-users" "ciphertext=vault:v1:KKZvc6UoTS9i2skreK7D7lhYSiwH9Vs+ZiRkC+ZjLlNt4uAr" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: PASSWORD_ALFA_NUMERIC_SPECIAL_CHARS
          {{ .Data.plaintext }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-sms_username: ""
        vault.hashicorp.com/agent-inject-template-sms_username: |
          {{- with secret "transit/git/decrypt/team9-ycs-users" "ciphertext=vault:v1:G+aVWZkt9LxOSQd3XaynN0L7GKifqml8y6kUiDwRF5jqJT91djBqOqSZ" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: PASSWORD_ALFA_NUMERIC_SPECIAL_CHARS
          {{ .Data.plaintext }}
          {{- end -}}
